/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CurrencyConfig, LanguageConfig, DestinationHighlight, PromotionOffer, Property, AddOn } from './types';

export const CURRENCIES: Record<string, CurrencyConfig> = {
  USD: { code: 'USD', symbol: '$', name: 'US Dollar', rateFromUSD: 1.0 },
  EUR: { code: 'EUR', symbol: '€', name: 'Euro', rateFromUSD: 0.92 },
  NGN: { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', rateFromUSD: 1520.0 },
  GBP: { code: 'GBP', symbol: '£', name: 'British Pound', rateFromUSD: 0.79 },
  JPY: { code: 'JPY', symbol: '¥', name: 'Japanese Yen', rateFromUSD: 155.0 },
};

export const LANGUAGES: Record<string, LanguageConfig> = {
  EN: { code: 'EN', name: 'English (US)', nativeName: 'English' },
  ES: { code: 'ES', name: 'Spanish', nativeName: 'Español' },
  FR: { code: 'FR', name: 'French', nativeName: 'Français' },
  DE: { code: 'DE', name: 'German', nativeName: 'Deutsch' },
  JA: { code: 'JA', name: 'Japanese', nativeName: '日本語' },
};

export const PROMOTIONAL_OFFERS: PromotionOffer[] = [
  {
    id: 'promo-1',
    title: 'Early Summer Getaway',
    badge: '15% off or more',
    discountPercent: 15,
    description: 'Save at participating properties worldwide when booking 14+ days in advance.',
    validUntil: 'Nov 30, 2026',
    bgGradient: 'from-blue-600 to-indigo-800',
    code: 'SUMMER15',
  },
  {
    id: 'promo-2',
    title: 'Genius Member Tier 2 VIP',
    badge: 'Free Breakfast Included',
    discountPercent: 20,
    description: 'Unlock complimentary room upgrades, priority late check-out, and curated morning buffets.',
    validUntil: 'Dec 31, 2026',
    bgGradient: 'from-sky-600 to-blue-900',
    code: 'GENIUSVIP',
  },
  {
    id: 'promo-3',
    title: 'Extended Stay Luxury',
    badge: 'Stay 5+ Nights, Save 25%',
    discountPercent: 25,
    description: 'Ideal for digital nomads and leisure travelers looking for deeper comfort and dedicated workstations.',
    validUntil: 'Oct 31, 2026',
    bgGradient: 'from-blue-700 to-slate-900',
    code: 'LONGSTAY25',
  },
  {
    id: 'promo-4',
    title: 'Weekend Alpine & Coastal Escapes',
    badge: 'Free Airport Transfer',
    discountPercent: 10,
    description: 'Complimentary private luxury chauffeur transfer on select chalet and villa bookings.',
    validUntil: 'Jan 15, 2027',
    bgGradient: 'from-indigo-600 to-sky-900',
    code: 'TRANSFERSAVE',
  },
];

export const DESTINATIONS: DestinationHighlight[] = [
  {
    id: 'dest-paris',
    name: 'Paris',
    country: 'France',
    propertyCount: 1420,
    tagline: 'Haussmann boulevards, world-class gastronomy & Louvre arts',
    image: '/src/assets/images/destination_paris_1791457864605.jpg',
    coordinates: { lat: 48.8566, lng: 2.3522 },
  },
  {
    id: 'dest-tokyo',
    name: 'Tokyo',
    country: 'Japan',
    propertyCount: 1890,
    tagline: 'Futuristic skylines, serene shrines & Ginza boutique stays',
    image: '/src/assets/images/destination_tokyo_1791457875474.jpg',
    coordinates: { lat: 35.6762, lng: 139.6503 },
  },
  {
    id: 'dest-bali',
    name: 'Bali',
    country: 'Indonesia',
    propertyCount: 860,
    tagline: 'Cliffside ocean infinity pools, tropical jungles & wellness',
    image: '/src/assets/images/property_bali_villa_1791457885264.jpg',
    coordinates: { lat: -8.4095, lng: 115.1889 },
  },
  {
    id: 'dest-zermatt',
    name: 'Zermatt & Swiss Alps',
    country: 'Switzerland',
    propertyCount: 340,
    tagline: 'Matterhorn glacier views, cozy timber chalets & luxury spas',
    image: '/src/assets/images/property_swiss_chalet_1791457897210.jpg',
    coordinates: { lat: 45.9765, lng: 7.7491 },
  },
];

export const ADD_ONS: AddOn[] = [
  {
    id: 'addon-transfer',
    name: 'Private Luxury Airport Chauffeur',
    description: 'Personal driver greets you at the arrivals terminal with baggage assistance.',
    priceUSD: 45,
    perStayOrNight: 'per_stay',
  },
  {
    id: 'addon-early-checkin',
    name: 'Guaranteed Early Check-in (11:00 AM)',
    description: 'Arrive early and settle straight into your suite without waiting for standard check-in.',
    priceUSD: 30,
    perStayOrNight: 'per_stay',
  },
  {
    id: 'addon-breakfast',
    name: 'Artisan Gourmet Breakfast Buffet',
    description: 'Fresh organic pastries, seasonal fruit, made-to-order eggs, and specialty roast coffee daily.',
    priceUSD: 24,
    perStayOrNight: 'per_night',
  },
  {
    id: 'addon-late-checkout',
    name: 'Relaxed Late Check-out (3:00 PM)',
    description: 'Enjoy a leisurely final morning and pack at your own pace.',
    priceUSD: 25,
    perStayOrNight: 'per_stay',
  },
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-paris-grand',
    hostId: 'host-1',
    hostName: 'Maison de Prestige Hospitality',
    name: 'Hotel Le Grand Boulevard & Spa',
    tagline: '5-Star Parisian luxury with panoramic balcony views of Boulevard Haussmann',
    description: 'Nestled in the prestigious 8th arrondissement, Hotel Le Grand Boulevard seamlessly blends 19th-century Haussmann elegance with contemporary minimalist luxury. Enjoy a subterranean marble spa, Michelin-star dining, and hand-crafted breakfast served directly on your private iron-lace balcony overlooking the city.',
    propertyType: 'Hotel',
    starRating: 5,
    reviewScore: 9.6,
    reviewCount: 1482,
    reviewSummary: 'Exceptional',
    address: '14 Boulevard Haussmann, 8th Arrondissement',
    city: 'Paris',
    country: 'France',
    distanceFromCenter: '0.6 km from Opera Garnier',
    coordinates: { lat: 48.8722, lng: 2.3332 },
    images: [
      '/src/assets/images/destination_paris_1791457864605.jpg',
      '/src/assets/images/destination_tokyo_1791457875474.jpg',
      '/src/assets/images/property_swiss_chalet_1791457897210.jpg',
    ],
    featuredImage: '/src/assets/images/destination_paris_1791457864605.jpg',
    featured: true,
    geniusDiscount: 15,
    amenities: ['Free Wi-Fi', 'Breakfast Included', 'Air Conditioning', 'Spa & Wellness', 'Airport Shuttle', 'Private Balcony', 'Fitness Center'],
    categoryScores: {
      cleanliness: 9.8,
      location: 9.9,
      service: 9.7,
      value: 9.2,
      comfort: 9.6,
    },
    startingPricePerNight: 320,
    rooms: [
      {
        id: 'room-paris-1',
        propertyId: 'prop-paris-grand',
        name: 'Deluxe Boulevard King Suite with Balcony',
        description: 'Features a private wrought-iron balcony overlooking Haussmann boulevards, Italian marble soaking tub, and custom featherbedding.',
        roomType: 'Suite',
        bedType: '1 Extra-large Double Bed (King)',
        sizeSqM: 42,
        maxOccupancy: 2,
        basePricePerNight: 320,
        originalPricePerNight: 380,
        totalInventory: 6,
        availableInventory: 4,
        mealPlan: 'Breakfast Included',
        cancellationPolicy: 'Free Cancellation',
        features: ['Balcony with City View', 'Free Wi-Fi', 'Soundproofing', 'Nespresso Coffee Machine', 'Dyson Supersonic Hairdryer'],
        image: '/src/assets/images/destination_paris_1791457864605.jpg',
      },
      {
        id: 'room-paris-2',
        propertyId: 'prop-paris-grand',
        name: 'Prestige Executive Junior Suite',
        description: 'Spacious open-concept living area, separate vanity room, rainfall shower, and complimentary afternoon tea service.',
        roomType: 'Junior Suite',
        bedType: '1 King Bed + 1 Sofa Bed',
        sizeSqM: 55,
        maxOccupancy: 3,
        basePricePerNight: 460,
        originalPricePerNight: 540,
        totalInventory: 4,
        availableInventory: 2,
        mealPlan: 'Breakfast Included',
        cancellationPolicy: 'Free Cancellation',
        features: ['Courtyard Garden View', 'Walk-in Wardrobe', 'Champagne Welcome', 'Complimentary Minibar'],
        image: '/src/assets/images/destination_paris_1791457864605.jpg',
      },
    ],
    reviews: [
      {
        id: 'rev-p1',
        userId: 'u-101',
        userName: 'Eleanor Vance',
        userCountry: 'United Kingdom',
        travelerType: 'Couple',
        rating: 9.8,
        title: 'Magical morning coffee with views over Haussmann',
        comment: 'The location could not be better—five minutes walk to the Opera and Galeries Lafayette. The balcony suite was quiet, pristine, and the breakfast basket with warm croissants was a dream.',
        stayDate: 'September 2026',
        verified: true,
      },
      {
        id: 'rev-p2',
        userId: 'u-102',
        userName: 'Julian Martinez',
        userCountry: 'Spain',
        travelerType: 'Business',
        rating: 9.4,
        title: 'Seamless check-in and ultra-fast high-speed Wi-Fi',
        comment: 'Traveled for work meetings in the financial district. The desk setup was ergonomic, concierge arranged a private airport transfer without delay, and the spa is exceptional.',
        stayDate: 'August 2026',
        verified: true,
      },
    ],
  },
  {
    id: 'prop-tokyo-lumina',
    hostId: 'host-2',
    hostName: 'Komorebi Luxury Group',
    name: 'The Lumina Ginza Boutique Hotel',
    tagline: 'Modern Japanese minimalism meets sky-high neon tranquility in Ginza',
    description: 'Perched in the heart of Ginza’s premier shopping district, The Lumina combines minimalist Hinoki cypress woods with panoramic floor-to-ceiling glass windows overlooking Tokyo’s gleaming skyline. Features an authentic matcha tea lounge, deep soaking Hinoki tubs, and bespoke concierge.',
    propertyType: 'Hotel',
    starRating: 5,
    reviewScore: 9.5,
    reviewCount: 920,
    reviewSummary: 'Superb',
    address: '6-10-1 Ginza, Chuo City',
    city: 'Tokyo',
    country: 'Japan',
    distanceFromCenter: '0.2 km from Ginza Station',
    coordinates: { lat: 35.6712, lng: 139.765 },
    images: [
      '/src/assets/images/destination_tokyo_1791457875474.jpg',
      '/src/assets/images/destination_paris_1791457864605.jpg',
      '/src/assets/images/property_bali_villa_1791457885264.jpg',
    ],
    featuredImage: '/src/assets/images/destination_tokyo_1791457875474.jpg',
    featured: true,
    geniusDiscount: 10,
    amenities: ['Free Wi-Fi', 'Breakfast Included', 'Air Conditioning', 'Fitness Center', 'Spa & Wellness', 'Airport Shuttle'],
    categoryScores: {
      cleanliness: 9.9,
      location: 9.8,
      service: 9.6,
      value: 9.1,
      comfort: 9.7,
    },
    startingPricePerNight: 285,
    rooms: [
      {
        id: 'room-tokyo-1',
        propertyId: 'prop-tokyo-lumina',
        name: 'Skyline Panorama Superior Room',
        description: 'Floor-to-ceiling glass framing Ginza’s neon nights, tatami seating nook, and Japanese deep onsen soaking bath.',
        roomType: 'Deluxe',
        bedType: '1 Extra-large Double Bed (King)',
        sizeSqM: 36,
        maxOccupancy: 2,
        basePricePerNight: 285,
        originalPricePerNight: 320,
        totalInventory: 8,
        availableInventory: 5,
        mealPlan: 'Breakfast Included',
        cancellationPolicy: 'Free Cancellation',
        features: ['Skyline Panorama', 'Aromatherapy Diffuser', 'Yukata Robes & Slippers', 'Bose Sound System'],
        image: '/src/assets/images/destination_tokyo_1791457875474.jpg',
      },
      {
        id: 'room-tokyo-2',
        propertyId: 'prop-tokyo-lumina',
        name: 'Zen Premier Corner Suite',
        description: 'Dual-aspect corner suite with 270-degree vista towards Tokyo Tower and Imperial Palace gardens.',
        roomType: 'Executive Suite',
        bedType: '1 Super King Bed',
        sizeSqM: 60,
        maxOccupancy: 3,
        basePricePerNight: 440,
        originalPricePerNight: 510,
        totalInventory: 3,
        availableInventory: 1,
        mealPlan: 'Breakfast Included',
        cancellationPolicy: 'Free Cancellation',
        features: ['270-degree Views', 'Personal Tea Master Service', 'Shoji Screens', 'Complimentary Cocktail Hour'],
        image: '/src/assets/images/destination_tokyo_1791457875474.jpg',
      },
    ],
    reviews: [
      {
        id: 'rev-t1',
        userId: 'u-103',
        userName: 'Kenji Takahashi',
        userCountry: 'United States',
        travelerType: 'Solo',
        rating: 9.7,
        title: 'Unbelievable skyline view and serene Japanese craftsmanship',
        comment: 'The silence inside the room is absolute despite being right above Ginza’s bustling streets. The Japanese breakfast set was Michelin-worthy.',
        stayDate: 'October 2026',
        verified: true,
      },
    ],
  },
  {
    id: 'prop-bali-azure',
    hostId: 'host-3',
    hostName: 'Azure Cliffside Estates',
    name: 'Uluwatu Cliff Azure Sanctuary Villa',
    tagline: 'Private infinity pool estate hanging dramatically over turquoise Indian Ocean waves',
    description: 'Set on the limestone cliffs of southern Bali, Azure Sanctuary offers uninterrupted sunset panoramas over Uluwatu surf breaks. Features open-air teak pavilions, private 15-meter freshwater infinity pool, personal butler, and cliffside firepit.',
    propertyType: 'Villa',
    starRating: 5,
    reviewScore: 9.8,
    reviewCount: 640,
    reviewSummary: 'Exceptional',
    address: 'Jalan Labuan Sait, Uluwatu',
    city: 'Bali',
    country: 'Indonesia',
    distanceFromCenter: '1.2 km from Uluwatu Temple',
    coordinates: { lat: -8.8142, lng: 115.0884 },
    images: [
      '/src/assets/images/property_bali_villa_1791457885264.jpg',
      '/src/assets/images/property_swiss_chalet_1791457897210.jpg',
      '/src/assets/images/destination_paris_1791457864605.jpg',
    ],
    featuredImage: '/src/assets/images/property_bali_villa_1791457885264.jpg',
    featured: true,
    geniusDiscount: 20,
    amenities: ['Swimming Pool', 'Ocean View', 'Free Wi-Fi', 'Breakfast Included', 'Airport Shuttle', 'Spa & Wellness', 'Private Balcony'],
    categoryScores: {
      cleanliness: 9.9,
      location: 9.9,
      service: 9.8,
      value: 9.4,
      comfort: 9.9,
    },
    startingPricePerNight: 410,
    rooms: [
      {
        id: 'room-bali-1',
        propertyId: 'prop-bali-azure',
        name: 'Private Pool Cliff Villa with Ocean View',
        description: 'Complete standalone luxury villa with 15m private infinity pool, outdoor sunken lounge, outdoor shower, and direct cliff views.',
        roomType: 'Villa',
        bedType: '1 Extra-large Double Bed (King)',
        sizeSqM: 110,
        maxOccupancy: 2,
        basePricePerNight: 410,
        originalPricePerNight: 512,
        totalInventory: 5,
        availableInventory: 2,
        mealPlan: 'Breakfast Included',
        cancellationPolicy: 'Free Cancellation',
        features: ['15m Private Infinity Pool', 'Floating Breakfast Option', '24/7 Butler Service', 'Sunset Deck'],
        image: '/src/assets/images/property_bali_villa_1791457885264.jpg',
      },
      {
        id: 'room-bali-2',
        propertyId: 'prop-bali-azure',
        name: 'Two-Bedroom Presidential Cliffside Estate',
        description: 'Dual pavilion estate with private chef kitchen, infinity lap pool, and panoramic sunset gazebo.',
        roomType: 'Grand Villa',
        bedType: '2 King Beds',
        sizeSqM: 220,
        maxOccupancy: 4,
        basePricePerNight: 780,
        originalPricePerNight: 980,
        totalInventory: 2,
        availableInventory: 1,
        mealPlan: 'All Inclusive',
        cancellationPolicy: 'Free Cancellation',
        features: ['Private Chef Service', 'Expansive Lawn & Infinity Pool', 'Bespoke Spa Treatments Included'],
        image: '/src/assets/images/property_bali_villa_1791457885264.jpg',
      },
    ],
    reviews: [
      {
        id: 'rev-b1',
        userId: 'u-104',
        userName: 'Aria Montgomery',
        userCountry: 'Australia',
        travelerType: 'Couple',
        rating: 10.0,
        title: 'The sunset from the infinity pool will stay with us forever',
        comment: 'We stayed for our honeymoon and were completely blown away. The butler was attentive without ever being intrusive, and watching the Uluwatu waves crash beneath us was unreal.',
        stayDate: 'September 2026',
        verified: true,
      },
    ],
  },
  {
    id: 'prop-swiss-matterhorn',
    hostId: 'host-4',
    hostName: 'Alpine Heritage Lodges',
    name: 'Chalet Matterhorn Royal Alpine Lodge',
    tagline: 'Ski-in ski-out luxury timber sanctuary with unobstructed Matterhorn peak panorama',
    description: 'Positioned above the car-free mountain village of Zermatt, Chalet Matterhorn Royal Alpine Lodge marries rough-hewn Swiss stone pine timbers with floor-to-ceiling glass framing the iconic Matterhorn. Warm up by the double-sided fireplace or soak in the heated outdoor mountain-view jacuzzi.',
    propertyType: 'Chalet',
    starRating: 5,
    reviewScore: 9.7,
    reviewCount: 480,
    reviewSummary: 'Exceptional',
    address: 'Oberer Mattenweg 22, Zermatt',
    city: 'Zermatt & Swiss Alps',
    country: 'Switzerland',
    distanceFromCenter: '0.4 km from Sunnegga Funicular',
    coordinates: { lat: 45.981, lng: 7.748 },
    images: [
      '/src/assets/images/property_swiss_chalet_1791457897210.jpg',
      '/src/assets/images/destination_paris_1791457864605.jpg',
      '/src/assets/images/destination_tokyo_1791457875474.jpg',
    ],
    featuredImage: '/src/assets/images/property_swiss_chalet_1791457897210.jpg',
    featured: true,
    geniusDiscount: 15,
    amenities: ['Free Wi-Fi', 'Breakfast Included', 'Spa & Wellness', 'Private Balcony', 'Airport Shuttle', 'Swimming Pool'],
    categoryScores: {
      cleanliness: 9.9,
      location: 9.9,
      service: 9.7,
      value: 9.3,
      comfort: 9.8,
    },
    startingPricePerNight: 490,
    rooms: [
      {
        id: 'room-swiss-1',
        propertyId: 'prop-swiss-matterhorn',
        name: 'Matterhorn Alpine Suite with Heated Terrace',
        description: 'Features genuine Swiss stone pine fragrance, heated timber terrace, roaring ethanol fireplace, and standalone cedar tub.',
        roomType: 'Suite',
        bedType: '1 Extra-large Double Bed (King)',
        sizeSqM: 52,
        maxOccupancy: 2,
        basePricePerNight: 490,
        originalPricePerNight: 575,
        totalInventory: 4,
        availableInventory: 3,
        mealPlan: 'Breakfast Included',
        cancellationPolicy: 'Free Cancellation',
        features: ['Matterhorn Direct View', 'Heated Outdoor Jacuzzi Access', 'Ski Storage & Boot Dryers', 'Swiss Fondue Evening'],
        image: '/src/assets/images/property_swiss_chalet_1791457897210.jpg',
      },
      {
        id: 'room-swiss-2',
        propertyId: 'prop-swiss-matterhorn',
        name: 'Grand Alpine Penthouse Chalet',
        description: 'Vaulted timber ceilings, panoramic glass gable wall framing the Alps, private cedar sauna, and dedicated sommelier service.',
        roomType: 'Penthouse',
        bedType: '2 King Beds',
        sizeSqM: 140,
        maxOccupancy: 4,
        basePricePerNight: 950,
        originalPricePerNight: 1150,
        totalInventory: 1,
        availableInventory: 1,
        mealPlan: 'Half Board',
        cancellationPolicy: 'Free Cancellation',
        features: ['Private Sauna & Outdoor Hot Tub', 'Ski-in Ski-out Access', 'Curated Wine Cellar'],
        image: '/src/assets/images/property_swiss_chalet_1791457897210.jpg',
      },
    ],
    reviews: [
      {
        id: 'rev-s1',
        userId: 'u-105',
        userName: 'Christoph Weber',
        userCountry: 'Germany',
        travelerType: 'Couple',
        rating: 9.9,
        title: 'Sitting in the outdoor heated jacuzzi looking at the Matterhorn was sublime',
        comment: 'Every detail from the heated ski boot warmers to the gourmet breakfast was executed with Swiss perfection. We will be returning every winter.',
        stayDate: 'February 2026',
        verified: true,
      },
    ],
  },
  {
    id: 'prop-ny-skyline',
    hostId: 'host-5',
    hostName: 'Manhattan Sky Hospitality',
    name: 'The Highline Glasshouse & Lofts',
    tagline: 'Modern architectural lofts overlooking the Hudson River & Highline Park',
    description: 'Located in West Chelsea, The Highline Glasshouse features industrial-chic steel architecture, museum-curated art collections, and rooftop cocktail terrace overlooking the Hudson River sunsets.',
    propertyType: 'Apartment',
    starRating: 4,
    reviewScore: 9.3,
    reviewCount: 810,
    reviewSummary: 'Wonderful',
    address: '520 West 28th Street, Chelsea',
    city: 'New York',
    country: 'United States',
    distanceFromCenter: '1.1 km from Times Square',
    coordinates: { lat: 40.752, lng: -74.004 },
    images: [
      '/src/assets/images/destination_paris_1791457864605.jpg',
      '/src/assets/images/destination_tokyo_1791457875474.jpg',
    ],
    featuredImage: '/src/assets/images/destination_paris_1791457864605.jpg',
    featured: false,
    geniusDiscount: 10,
    amenities: ['Free Wi-Fi', 'Air Conditioning', 'Fitness Center', 'Kitchenette', 'Pet Friendly'],
    categoryScores: {
      cleanliness: 9.6,
      location: 9.8,
      service: 9.2,
      value: 8.9,
      comfort: 9.4,
    },
    startingPricePerNight: 295,
    rooms: [
      {
        id: 'room-ny-1',
        propertyId: 'prop-ny-skyline',
        name: 'Chelsea Artist Studio Loft with Full Kitchen',
        description: 'Exposed concrete, floor-to-ceiling glass, designer sofa, and chef-equipped kitchen with marble island.',
        roomType: 'Loft Studio',
        bedType: '1 Queen Bed',
        sizeSqM: 48,
        maxOccupancy: 2,
        basePricePerNight: 295,
        originalPricePerNight: 330,
        totalInventory: 5,
        availableInventory: 3,
        mealPlan: 'Room Only',
        cancellationPolicy: 'Free Cancellation',
        features: ['Designer Kitchen', 'Highline Park Views', 'Washer / Dryer in Unit', 'Fast Fiber Wi-Fi'],
        image: '/src/assets/images/destination_paris_1791457864605.jpg',
      },
    ],
    reviews: [
      {
        id: 'rev-ny1',
        userId: 'u-106',
        userName: 'David Miller',
        userCountry: 'Canada',
        travelerType: 'Business',
        rating: 9.3,
        title: 'Perfect base for creative work in Chelsea',
        comment: 'Steps from art galleries, top dining, and the Hudson River promenade. The workspace was silent and comfortable.',
        stayDate: 'July 2026',
        verified: true,
      },
    ],
  },
];
